### ISSUE TITLE
Bug Report:  jaeger-tracer-lib 1.1-SNAPSHOT not compatible with Payara 5.2021.4

### ISSUE THREAD

**Issue by jefrajames** [payara/ecosystem-support#27]
# Description #
----------
When using _jaeger-tracer-lib 1.1-SNAPSHOT_  with  _Payara Micro 5.2021.4_, no such method error on _io.opentracing.ScopeManager.active_ occurs at runtime.

According to my tests, it works with previous Payara versions: 5.194, 5.201, 5.2020.7.

It seems that the OpenTracing version used by Payara 5.2021.4 is not compatible with _jaeger-tracer-lib 1.1-SNAPSHOT_   (probably _io.jaegertracing 0.30.6_).

## Expected Outcome ##

OpenTracing messages should be sent to the configured Jaeger instance.

## Current Outcome ##

A runtime error occurs and no trace is sent to Jaeger.

Here is stack trace describing the issue when generating a trace:
`StandardWrapperValve[org.jefrajames.smartbank.config.JAXRSConfiguration]: Servlet.service() for servlet org.jefrajames.smartbank.config.JAXRSConfiguration threw exception
java.lang.NoSuchMethodError: io/opentracing/ScopeManager.active()Lio/opentracing/Scope; (loaded from file:/var/folders/c_/bnsc1b511hn7d6tz5vxc61gw0000gn/T/payaramicro-rt18362290624374404426tmp/runtime/opentracing-repackaged.jar by fish.payara.micro.boot.loader.ExplodedURLClassloader@9179f981) called from class io.jaegertracing.internal.JaegerTracer (loaded from file:/Users/powerj/javadev/demo/bjug-2021/bin/./payara-dir/lib/jaeger-tracer-lib-1.1-SNAPSHOT-jar-with-dependencies.jar by fish.payara.micro.boot.loader.ExplodedURLClassloader@9179f981)`

## Environment ##

- openjdk version "11.0.10" 2021-01-19
- Payara Micro 5.2021.4
- jaeger-tracing downloaded from https://github.com/payara/ecosystem-jaeger-tracing, built locally
- use of the Jar file with dependencies
- configuration in a postboot file: `set-requesttracing-configuration --enabled true --dynamic true`.

**Comment by rdebusscher** [comment]
Hi Jean-Francois,

Now that we have update both Payara Community and Enterprise, we have an updated version of this Jaeger Integration.  See https://github.com/payara/ecosystem-jaeger-tracing/pull/3

Regards
Rudy

**Comment by fturizo** [comment]
Closing this issue due to inactivity.
